env: "dev"

# Resource group
resource_group_name: "dev-resource-group"
location: "Australia Central"

# Storage
storage_account_name: "myappstorage"
storage_container_name: "terraform-state-file"
key: "terraform.tfstate"

# Front Door
frontdoor_profile_name: "dev-front-door-profile"

# Virtual network
hub_vnet_name: "hub-vnet"
address_space:
- "10.0.0.0/16"

spoke_vnet_name: "spoke-vnet"
address_space:
- "10.1.0.0/16"

# Auzre Firewall subnet
afw_subnet: "afw-subnet"
afw_address_prefixes:
- "10.0.0.0/24"

# Application Gateway subnet
agw_subnet: "agw-subnet"
agw_address_prefixes:
- "10.0.1.0/24"

# Private subnets
web_subnet_name: "web-subnet"
app_subnet_name: "app-subnet"
db_subnet_name: "db-subnet"

web_address_prefixes:
- "10.1.1.0/24"
app_address_prefixes:
- "10.1.2.0/24"
db_address_prefixes:
- "10.1.3.0/24"

# Public subnets
bastion_subnet_name: "bastion-subnet"
bastion_address_prefixes:
- "10.1.11.0/24"
