env: "dev"

# rg
resource_group_name: "dev-resource-group"
location: "Australia Central"

# storage
storage_account_name: "myappstorage"
storage_container_name: "terraform-state-file"
key: "terraform.tfstate"

# vnet
vnet_name: "vnet"
address_space:
- "10.0.0.0/16"
