- name: Render Terraform Templates for Different Environments
  hosts: localhost
  gather_facts: no
  vars:
    env: "{{ lookup('env', 'ENV') | default('dev', true) }}" # Default to 'dev' if ENV is not set
  tasks:
  - name: Load environment-specific variables
    include_vars:
      file: "vars/{{ env }}.yaml"

  - name: Find all Terraform template files
    find:
      paths: "{{ playbook_dir }}"
      patterns: "*.tf.j2"
    register: template_files

  - name: Render Terraform templates
    template:
      src: "{{ item.path }}"
      dest: "{{ item.path | basename | regex_replace('.j2$', '.tf') }}"
    loop: "{{ template_files.files }}"

  - name: Debug rendered files
    command: find "{{ playbook_dir }}" -name "*.tf"
    register: rendered_tf_files

  - name: Show rendered .tf files
    debug:
      msg: "{{ rendered_tf_files.stdout_lines }}"
