name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
    render-and-apply:
        runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
        uses: actions/checkout@v4

        - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
        
        - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: latest
        
        # 1rg
        - name: Run Ansible to Render Terraform Template
        run: ansible-playbook -i localhost, -e "@azure/template/dev/1rg/vars.yml" zaure/template/dev/1rg/rg.yml
        
        - name: Initialize Terraform
        run: |
            cd azure/template/dev/1rg
            terraform init
          
        - name: Plan Terraform
        run: |
            cd azure/template/dev/1rg
            terraform plan
          
        - name: Apply Terraform
        run: |
            cd azure/template/dev/1rg
            terraform apply -auto-approve
