name: Dev Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm deletion of the dev environment'
        default: 'no'
        required: true
        type: string

jobs:
  render-and-delete:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'yes' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      
      - name: Run Ansible to Render Terraform Template
        run: |
          ansible-playbook azure/template/playbook.yml --syntax-check
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i azure/template/inventory/envs.ini, -e "@azure/template/vars/dev.yaml" azure/template/playbook.yml
      
      - name: Initialize Terraform
        working-directory: ./azure/template/templates
        run: |
          terraform init \
            -backend-config="resource_group_name=dev-resource-group" \
            -backend-config="storage_account_name=devmyappstorage" \
            -backend-config="container_name=dev-terraform-state-file" \
            -backend-config="key=terraform.tfstate"
        env:
            ARM_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.DEV_AZURE_TENANT_ID }}
 
      - name: Terraform Destroy
        # if: github.ref == 'refs/heads/main'
        working-directory: ./azure/template/templates
        run: |
          terraform destroy -auto-approve
        env:
            ARM_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.DEV_AZURE_TENANT_ID }}
