name: Staging Asset Opreate Creation

on:
  push:
    branches:
      - add-app-service
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      
      - name: Initialize Terraform
        run: |
          terraform force-unlock 1a95d384-46ec-028c-2c9c-c4975b007961
          terraform init \
            -backend-config="resource_group_name=asset-operate" \
            -backend-config="storage_account_name=assetc4e285" \
            -backend-config="container_name=asset-operate-terraform-state-file" \
            -backend-config="key=terraform.tfstate"
        env:
            ARM_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.DEV_AZURE_TENANT_ID }}
      
      - name: Terraform Format Check
        working-directory: ./azure/asset-operate/tf-configuration
        run: |
          terraform fmt
      
      - name: Terraform Validate
        working-directory: ./azure/asset-operate/tf-configuration
        run: |
          terraform validate

      - name: Plan Terraform
        working-directory: ./azure/asset-operate/tf-configuration
        run: |
          terraform plan -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.DEV_AZURE_TENANT_ID }}

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        working-directory: ./azure/asset-operate/tf-configuration
        run: |
          terraform apply -auto-approve tfplan
        env:
            ARM_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.DEV_AZURE_TENANT_ID }}
